/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/FINAL_ROOM.gltf 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/FINAL_ROOM.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={100} near={0.1} fov={22.895} position={[11.614, 10.697, 14.13]} rotation={[-0.521, 0.567, 0.299]} />
      <pointLight intensity={0.0359} decay={2} color="#ffecce" position={[-1.824, 1.375, 2.559]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={0.0794} decay={2} color="#ffc5a0" position={[1.997, 2.794, -1.89]} rotation={[-Math.PI / 2, 0, 0]} />
      <directionalLight intensity={0.0546} decay={2} color="#ffe2eb" position={[-3.635, 4.308, -8.041]} rotation={[-2.564, -0.282, -0.154]} target={nodes['*back_light'].target}>
        <primitive object={nodes['*back_light'].target} position={[0, 0, -1]} />
      </directionalLight>
      <pointLight intensity={5.0166} decay={2} color="#ffd8c4" position={[2.253, 4.105, 2.354]} rotation={[-3.088, -0.253, 0.935]} scale={0.705} />
      <pointLight intensity={0.1881} decay={2} color="#ffd8cc" position={[3.246, 1.523, -1.692]} rotation={[2.681, -0.037, -2.703]} />
      <pointLight intensity={0.1881} decay={2} color="#ffd8cc" position={[5.624, 1.329, -1.132]} rotation={[2.681, -0.037, -2.703]} />
      <group position={[-0.044, 2.227, -1.215]} rotation={[2.924, -0.298, -0.198]} scale={[-0.034, -0.031, -0.047]}>
        {/* fox */}
        <mesh geometry={nodes.Cube029.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Cube029_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube029_2.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Cube029_3.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Cube029_4.geometry} material={materials['Material.024']} />
        <mesh geometry={nodes.Cube029_5.geometry} material={materials['Material.026']} />
        <mesh geometry={nodes.Cube029_6.geometry} material={materials['Material.025']} />
      </group>
      <group position={[3.95, 0.886, -0.801]} rotation={[-0.208, -0.003, 0.025]}>
        {/* board outside */}
        <mesh geometry={nodes.Cube066.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube066_1.geometry} material={materials['pale white']} />
        <mesh geometry={nodes.Cube066_2.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Text.geometry} material={materials['Material.019']} position={[-0.745, 1.75, -0.021]} rotation={[Math.PI / 2, 0, 0]} scale={0.832}>
          <mesh geometry={nodes.GN_Instance.geometry} material={materials['Material.019']} />
        </mesh>
      </group>
      <group position={[-0.152, 2.292, -0.212]} rotation={[0, 1.328, 0]} scale={0.478}>
        {/* register */}
        <mesh geometry={nodes.Cube020.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Cube020_1.geometry} material={materials['light pink']} />
        <mesh geometry={nodes.Cube020_2.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Cube020_3.geometry} material={materials['Material.027']} />
      </group>
      <group position={[0, 2.5, 0]} scale={2.5}>
        {/* inner walls */}
        <mesh geometry={nodes.Cube002.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['dark brown']} />
      </group>
      <group position={[-2.315, 2.165, -1.384]} rotation={[0, -1.571, 0]} scale={[0.125, 0.144, 0.125]}>
        {/* plant */}
        <mesh geometry={nodes.Circle001.geometry} material={materials['room_floor.001']} />
        <mesh geometry={nodes.Circle001_1.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Circle001_2.geometry} material={materials.plant} />
      </group>
      <group position={[1.686, 2.039, -1.183]} rotation={[0, -1.571, 0]} scale={0.478}>
        {/* counter */}
        <mesh geometry={nodes.Cube006.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['pale white']} />
        <mesh geometry={nodes.Cube006_3.geometry} material={materials['Material.071']} />
      </group>
      <mesh geometry={nodes.lightstring.geometry} material={materials['Material.005']} position={[-3.359, 4.424, -0.034]} rotation={[Math.PI, 0, Math.PI]} scale={[1, 1, 2.242]}>
        {/* lights */}
        <group position={[-0.998, -0.159, 0.839]} rotation={[0, -1.571, 0]} scale={[0.031, 0.07, 0.07]}>
          <mesh geometry={nodes.Sphere010.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Sphere010_1.geometry} material={materials['room_floor.001']} />
          <mesh geometry={nodes.Sphere010_2.geometry} material={materials['room_floor.004']} />
          <mesh geometry={nodes.Sphere010_3.geometry} material={materials['Material.074']} />
        </group>
      </mesh>
      <group position={[0, 2.5, 0]} scale={2.5}>
        {/* floor */}
        <mesh geometry={nodes.Cube003.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.041']} />
      </group>
      <mesh geometry={nodes.plantvine.geometry} material={materials.plant} position={[0.29, 5.495, -2.667]} rotation={[0.014, 0.007, 0]} scale={[1.004, 1.003, 1]} />
      {/* plant vine */}
      <group position={[2.03, 3.194, -2.261]} rotation={[-Math.PI / 2, -0.419, -Math.PI / 2]} scale={[-0.141, -0.105, -0.141]}>
        {/* cups */}
        <mesh geometry={nodes.Cylinder005.geometry} material={materials['Material.047']} />
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Cylinder005_2.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cylinder005_3.geometry} material={materials['pale white']} />
        <mesh geometry={nodes.Cylinder005_4.geometry} material={materials['Material.046']} />
      </group>
      <group onClick={() => console.log('clicked bread')} position={[1.322, 2.19, 0.073]} rotation={[0, -0.4, 0]} scale={0.39}>
        {/* bread basket */}
        <mesh geometry={nodes.Plane141.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Plane141_1.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Plane141_2.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Plane141_3.geometry} material={materials['Bread.002']} />
        <mesh geometry={nodes.Plane141_4.geometry} material={materials['Bread.003']} />
      </group>
      <group onClick={() => console.log('clicked donuts')} position={[1.94, 1.931, -1.776]} rotation={[-1.053, -1.277, -1.224]} scale={0.802}>
        {/* right green donut */}
        <mesh geometry={nodes.Sphere011_1.geometry} material={materials['Material.030']} />
        <mesh geometry={nodes.Sphere011_2.geometry} material={materials['Material.031']} />
      </group>
      <group onClick={() => console.log('clicked donuts')} position={[1.842, 1.99, -0.783]} rotation={[0.964, 1.15, -0.849]} scale={[0.282, 0.361, 0.28]}>
        {/* tan donut */}
        <mesh geometry={nodes.Sphere022.geometry} material={materials['Material.033']} />
        <mesh geometry={nodes.Sphere022_1.geometry} material={materials['Material.032']} />
      </group>
      <group onClick={() => console.log('clicked donuts')} position={[1.978, 1.944, -1.342]} rotation={[-1.155, -1.277, -1.224]} scale={0.802}>
        {/* left green donut */}
        <mesh geometry={nodes.Sphere023.geometry} material={materials['Material.030']} />
        <mesh geometry={nodes.Sphere023_1.geometry} material={materials['Material.031']} />
      </group>
      <group onClick={() => console.log('clicked donuts')} position={[1.851, 2.479, -1.765]} rotation={[-2.582, 1.331, 3.132]} scale={0.167}>
        {/* pink donut */}
        <mesh geometry={nodes.Torus_1.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.Torus_2.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.Torus_3.geometry} material={materials['Material.027']} />
      </group>
      {/* left brown donut */}
      <mesh onClick={() => console.log('clicked donuts')} geometry={nodes.Torus007.geometry} material={materials['Bread.003']} position={[1.853, 2.483, -0.948]} rotation={[0.227, 0.412, -0.274]} scale={[0.129, 0.162, 0.13]} />
      {/* right brown donut */}
      <mesh onClick={() => console.log('clicked donuts')} geometry={nodes.Torus008.geometry} material={materials['Bread.003']} position={[1.873, 2.488, -1.354]} rotation={[-0.035, -0.34, -0.107]} scale={[0.129, 0.162, 0.13]} />
      <group onClick={() => console.log('clicked display glass')} position={[1.811, 2.333, -1.355]} rotation={[0, -1.571, 0]} scale={[0.73, 0.478, 0.478]}>
        {/* display glass */}
        <mesh geometry={nodes.Cube007.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials['dark brown']} />
      </group>
      <group onClick={() => console.log('clicked chalkboard')} position={[-0.629, 2.892, -2.625]} rotation={[0, -1.571, 0]} scale={[0.479, 0.473, 0.439]}>
        {/* chalkboard */}
        <mesh geometry={nodes.Cube025.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube025_1.geometry} material={materials['Material.012']} />
      </group>
      <group onClick={() => console.log('clicked photos section')} position={[-2.4, 2.157, 1.931]} rotation={[-0.104, 0.079, 3.009]} scale={[0.001, 0.108, 0.089]}>
        {/* photos section */}
        <mesh geometry={nodes.Cube057.geometry} material={materials['Material.076']} />
        <mesh geometry={nodes.Cube057_1.geometry} material={materials['dark brown.005']} />
        <mesh geometry={nodes.Cube057_2.geometry} material={materials['room_floor.001']} />
        <mesh geometry={nodes.Cube057_3.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube057_4.geometry} material={materials.plant} />
        <mesh geometry={nodes.Cube057_5.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube057_6.geometry} material={materials['dark brown']} />
        <mesh geometry={nodes.Cube057_7.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube057_8.geometry} material={materials['light pink']} />
        <mesh geometry={nodes.Cube057_9.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube057_10.geometry} material={materials['room_floor.004']} />
        <mesh geometry={nodes.Cube057_11.geometry} material={materials['room_floor.006']} />
        <mesh geometry={nodes.Cube057_12.geometry} material={materials['room_floor.007']} />
        <mesh geometry={nodes.Cube057_13.geometry} material={materials['room_floor.009']} />
        <mesh geometry={nodes.Cube057_14.geometry} material={materials['dark brown.001']} />
        <mesh geometry={nodes.Cube057_15.geometry} material={materials['room_floor.010']} />
        <mesh geometry={nodes.Cube057_16.geometry} material={materials['dark brown.002']} />
        <mesh geometry={nodes.Cube057_17.geometry} material={materials['room_floor.011']} />
        <mesh geometry={nodes.Cube057_18.geometry} material={materials['dark brown.003']} />
        <mesh geometry={nodes.Cube057_19.geometry} material={materials['room_floor.012']} />
        <mesh geometry={nodes.Cube057_20.geometry} material={materials['dark brown.004']} />
        <mesh geometry={nodes.Cube057_21.geometry} material={materials['room_floor.013']} />
      </group>
      <group position={[-1.196, 1.993, 1.423]} rotation={[0.005, -0.112, -0.002]} scale={[0.154, 0.154, 0.085]}>
        {/* mouse and table stuff */}
        <mesh onClick={() => console.log('clicked mouse')} geometry={nodes.BézierCurve002.geometry} material={materials.lightbrown} />
        <mesh geometry={nodes.BézierCurve002_1.geometry} material={materials['darkbrown.001']} />
        <mesh geometry={nodes.BézierCurve002_2.geometry} material={materials.darkbrown} />
        <mesh onClick={() => console.log('clicked mouse')} geometry={nodes.BézierCurve002_3.geometry} material={materials['pink.001']} />
        <mesh onClick={() => console.log('clicked mouse')} geometry={nodes.BézierCurve002_4.geometry} material={materials['lightbrown.001']} />
        <mesh onClick={() => console.log('clicked mouse')} geometry={nodes.BézierCurve002_5.geometry} material={materials.lightestbrown} />
        <mesh geometry={nodes.BézierCurve002_6.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.BézierCurve002_7.geometry} material={materials.pink} />
        <mesh geometry={nodes.BézierCurve002_8.geometry} material={materials['pale white']} />
        <mesh geometry={nodes.BézierCurve002_9.geometry} material={materials['Material.047']} />
        <mesh geometry={nodes.BézierCurve002_10.geometry} material={materials['dark brown']} />
        <mesh geometry={nodes.BézierCurve002_11.geometry} material={materials['room_floor.001']} />
        <mesh geometry={nodes.BézierCurve002_12.geometry} material={materials['Material.050']} />
      </group>
      <mesh onClick={() => console.log('clicked about text')} geometry={nodes.about_text.geometry} material={materials['Material.019']} position={[3.265, 2.302, -1.141]} rotation={[1.334, 0.035, 0.06]} scale={0.903} />
      <mesh onClick={() => console.log('clicked faq text')} geometry={nodes.faq_text.geometry} material={materials['Material.019']} position={[3.301, 1.287, -0.884]} rotation={[1.334, 0.035, 0.06]} scale={0.903} />
      <mesh onClick={() => console.log('clicked photos text')} geometry={nodes.photos_text.geometry} material={materials['Material.019']} position={[3.292, 1.533, -0.955]} rotation={[1.334, 0.035, 0.06]} scale={0.903} />
      <mesh onClick={() => console.log('clicked schedule text')} geometry={nodes.schedule_text.geometry} material={materials['Material.019']} position={[3.283, 1.779, -1.015]} rotation={[1.334, 0.035, 0.06]} scale={0.903} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.027']} position={[-0.365, 0.288, 0.243]} rotation={[-2.14, -0.809, 0.619]} scale={[1.2, 0.6, 1]} />
      <mesh onClick={() => console.log('clicked track text')} geometry={nodes.GN_Instance002.geometry} material={materials['Material.019']} position={[3.274, 2.037, -1.077]} rotation={[1.334, 0.035, 0.06]} scale={0.903} />
    </group>
  )
}

useGLTF.preload('/FINAL_ROOM.gltf')
