/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/final_2.gltf 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Model({
  onPointerOver,
  onPointerOut,
  onClick,
  hovered,
  ...props
}) {
  const { scene } = useGLTF("/final_2.gltf");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  return (
    <group {...props} dispose={null}>
      <pointLight
        intensity={0.18806}
        decay={2}
        color="#ffd8cc"
        position={[5.624, 1.329, -1.132]}
        rotation={[2.681, -0.037, -2.703]}
      />
      <directionalLight
        intensity={1.5436}
        decay={2}
        color="#ffdcad"
        position={[0.006, 4.718, 9.531]}
        rotation={[-0.528, 0.199, 0.413]}
        target={nodes["**sunlight"].target}
      >
        <primitive object={nodes["**sunlight"].target} position={[0, 0, -1]} />
      </directionalLight>
      <pointLight
        intensity={0.1087}
        decay={2}
        color="#ffecce"
        position={[-1.824, 1.375, 2.894]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={0.04239}
        decay={2}
        position={[1.997, 3.03, -1.306]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={0.08805}
        decay={2}
        color="#ffcabc"
        position={[1.83, 2.224, -1.085]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <directionalLight
        intensity={0.03278}
        decay={2}
        color="#ffe2eb"
        position={[-6.268, 4.308, 2.207]}
        rotation={[0.009, 0.281, 2.833]}
        target={nodes["**rear_sunlight"].target}
      >
        <primitive
          object={nodes["**rear_sunlight"].target}
          position={[0, 0, -1]}
        />
      </directionalLight>
      <directionalLight
        intensity={0.82}
        decay={2}
        color="#ffdbcd"
        position={[4.043, 5.693, -0.942]}
        rotation={[-1.792, 0.444, 0.05]}
        target={nodes["**sunlight_2"].target}
      >
        <primitive
          object={nodes["**sunlight_2"].target}
          position={[0, 0, -1]}
        />
      </directionalLight>
      <group
        position={[-2.45, 2.254, 2.161]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.036, 0.062, 0.036]}
      >
        <mesh
          geometry={nodes.Cylinder020.geometry}
          material={materials["room_floor.007"]}
        />
        <mesh
          geometry={nodes.Cylinder020_1.geometry}
          material={materials.plant}
        />
        <mesh
          geometry={nodes.Cylinder020_2.geometry}
          material={materials["room_floor.001"]}
        />
        <mesh
          geometry={nodes.Cylinder020_3.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          geometry={nodes.Cylinder020_4.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cylinder020_5.geometry}
          material={materials["dark brown"]}
        />
        <mesh
          geometry={nodes.Cylinder020_6.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          geometry={nodes.Cylinder020_7.geometry}
          material={materials["light pink"]}
        />
        <mesh
          geometry={nodes.Cylinder020_8.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Cylinder020_9.geometry}
          material={materials["room_floor.004"]}
        />
        <mesh
          geometry={nodes.Cylinder020_10.geometry}
          material={materials["room_floor.006"]}
        />
        <mesh
          geometry={nodes.Cylinder020_11.geometry}
          material={materials["Material.076"]}
        />
        <mesh
          geometry={nodes.Cylinder020_12.geometry}
          material={materials["dark brown.001"]}
        />
        <mesh
          geometry={nodes.Cylinder020_13.geometry}
          material={materials["room_floor.009"]}
        />
        <mesh
          geometry={nodes.Cylinder020_14.geometry}
          material={materials["dark brown.002"]}
        />
        <mesh
          geometry={nodes.Cylinder020_15.geometry}
          material={materials["room_floor.010"]}
        />
        <mesh
          geometry={nodes.Cylinder020_16.geometry}
          material={materials["room_floor.011"]}
        />
        <mesh
          geometry={nodes.Cylinder020_17.geometry}
          material={materials["dark brown.003"]}
        />
        <mesh
          geometry={nodes.Cylinder020_18.geometry}
          material={materials["room_floor.012"]}
        />
        <mesh
          geometry={nodes.Cylinder020_19.geometry}
          material={materials["dark brown.004"]}
        />
        <mesh
          geometry={nodes.Cylinder020_20.geometry}
          material={materials["dark brown.005"]}
        />
        <mesh
          geometry={nodes.Cylinder020_21.geometry}
          material={materials["room_floor.013"]}
        />
      </group>
      <group position={[0, 2.5, 0]} scale={2.5}>
        <mesh
          geometry={nodes.Cube026.geometry}
          material={materials["dark brown"]}
        />
        <mesh
          geometry={nodes.Cube026_1.geometry}
          material={materials["Material.030"]}
        />
        <mesh
          geometry={nodes.Cube026_2.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          geometry={nodes.Cube026_3.geometry}
          material={materials["Material.033"]}
        />
        <mesh
          geometry={nodes.Cube026_4.geometry}
          material={materials["Material.028"]}
        />
        <mesh
          geometry={nodes.Cube026_5.geometry}
          material={materials["Material.029"]}
        />
        <mesh
          geometry={nodes.Cube026_6.geometry}
          material={materials["Material.032"]}
        />
        <mesh
          geometry={nodes.Cube026_7.geometry}
          material={materials["Material.027"]}
        />
        <mesh
          geometry={nodes.Cube026_8.geometry}
          material={materials["Bread.006"]}
        />
        <mesh
          geometry={nodes.Cube026_9.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <group
        position={[-0.629, 2.892, -2.625]}
        rotation={[0, -1.571, 0]}
        scale={[0.479, 0.473, 0.439]}
      >
        <mesh
          geometry={nodes.Cube025.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Cube025_1.geometry}
          material={materials["Material.012"]}
        />
      </group>
      <group
        position={[0.138, 1.82, -0.711]}
        rotation={[0, 1.328, 0]}
        scale={0.311}
      >
        <mesh
          geometry={nodes.Cube021.geometry}
          material={materials["Material.014"]}
        />
        <mesh
          geometry={nodes.Cube021_1.geometry}
          material={materials["Material.027"]}
        />
        <mesh
          geometry={nodes.Cube021_2.geometry}
          material={materials["Material.016"]}
        />
        <mesh
          geometry={nodes.Cube021_3.geometry}
          material={materials["light pink"]}
        />
        <mesh
          geometry={nodes.Cube021_4.geometry}
          material={materials["Material.071"]}
        />
        <mesh
          geometry={nodes.Cube021_5.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          geometry={nodes.Cube021_6.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube021_7.geometry}
          material={materials["Material.041"]}
        />
        <mesh
          geometry={nodes.Cube021_8.geometry}
          material={materials["Material.009"]}
        />
        <mesh geometry={nodes.Cube021_9.geometry} material={materials.plant} />
        <mesh
          geometry={nodes.Cube021_10.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Cube021_11.geometry}
          material={materials["pale white"]}
        />
        <mesh
          geometry={nodes.Cube021_12.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Cube021_13.geometry}
          material={materials["dark brown"]}
        />
        <mesh
          geometry={nodes.Cube021_14.geometry}
          material={materials["room_floor.001"]}
        />
        <mesh
          geometry={nodes.Cube021_15.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cube021_16.geometry}
          material={materials["room_floor.004"]}
        />
        <mesh
          geometry={nodes.Cube021_17.geometry}
          material={materials["Material.074"]}
        />
        <mesh
          geometry={nodes.Cube021_18.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          geometry={nodes.Cube021_19.geometry}
          material={materials["Material.047"]}
        />
        <mesh
          geometry={nodes.Cube021_20.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[1.832, 1.788, 0.018]}
        rotation={[0.216, -0.992, -0.522]}
        scale={0.135}
      >
        <mesh
          geometry={nodes.Sphere018.geometry}
          material={materials["Bread.006"]}
        />
        <mesh
          geometry={nodes.Sphere018_1.geometry}
          material={materials["Material.017"]}
        />
        <mesh
          geometry={nodes.Sphere018_2.geometry}
          material={materials["Material.018"]}
        />
        <mesh
          geometry={nodes.Sphere018_3.geometry}
          material={materials["Bread.005"]}
        />
        <mesh
          geometry={nodes.Sphere018_4.geometry}
          material={materials["Material.020"]}
        />
      </group>
      <group
        position={[3.883, 2.023, -1.107]}
        rotation={[1.368, 0.05, -0.238]}
        scale={0.832}
      >
        <mesh
          geometry={nodes.Cube062.geometry}
          material={materials["pale white"]}
        />
        <mesh
          geometry={nodes.Cube062_1.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          geometry={nodes.Cube062_2.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          name="about_text"
          geometry={nodes["*about_text"].geometry}
          material={
            hovered === "about_text"
              ? materials["Material.005"]
              : materials["Material.019"]
          }
          position={[-0.752, 0.039, -0.301]}
          onPointerOver={(e) => onPointerOver(e)}
          onPointerOut={(e) => onPointerOut(e)}
          onClick={(e) => onClick(e)}
          scale={hovered === "about_text" ? [1.1, 1.1, 1.1] : [1, 1, 1]}
        >
          <mesh
            geometry={nodes.GN_Instance.geometry}
            material={
              hovered === "about_text"
                ? materials["Material.005"]
                : materials["Material.019"]
            }
          />
        </mesh>
        <mesh
          geometry={nodes["*blueprint_text"].geometry}
          material={materials["Material.019"]}
          position={[-0.906, 0.039, -0.645]}
        >
          <mesh
            geometry={nodes.GN_Instance_1.geometry}
            material={materials["Material.019"]}
          />
        </mesh>
        <mesh
          geometry={nodes["*faq_text"].geometry}
          material={materials["Material.019"]}
          position={[-0.752, 0.039, 0.855]}
        >
          <mesh
            geometry={nodes.GN_Instance_2.geometry}
            material={materials["Material.019"]}
          />
        </mesh>
        <mesh
          geometry={nodes["*photos_text"].geometry}
          material={materials["Material.019"]}
          position={[-0.752, 0.039, 0.575]}
        >
          <mesh
            geometry={nodes.GN_Instance_3.geometry}
            material={materials["Material.019"]}
          />
        </mesh>
        <mesh
          geometry={nodes["*schedule"].geometry}
          material={materials["Material.019"]}
          position={[-0.752, 0.039, 0.295]}
        >
          <mesh
            geometry={nodes.GN_Instance_4.geometry}
            material={materials["Material.019"]}
          />
        </mesh>
        <mesh
          geometry={nodes["*tracks_text"].geometry}
          material={materials["Material.019"]}
          position={[-0.752, 0.039, 0]}
        >
          <mesh
            geometry={nodes.GN_Instance_5.geometry}
            material={materials["Material.019"]}
          />
        </mesh>
      </group>
      <group
        position={[0.229, 2.168, -1.358]}
        rotation={[2.936, -1.234, -Math.PI]}
        scale={[0.196, 0.202, 0.195]}
      >
        <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
        <mesh
          geometry={nodes.Cube_1.geometry}
          material={materials["Material.019"]}
        />
        <mesh
          geometry={nodes.Cube_2.geometry}
          material={materials["Material.021"]}
        />
        <mesh
          geometry={nodes.Cube_3.geometry}
          material={materials["Material.023"]}
        />
        <mesh
          geometry={nodes.Cube_4.geometry}
          material={materials["Material.024"]}
        />
        <mesh
          geometry={nodes.Cube_5.geometry}
          material={materials["Material.026"]}
        />
        <mesh
          geometry={nodes.Cube_6.geometry}
          material={materials["Material.025"]}
        />
      </group>
      <group
        position={[-1.309, 1.784, 1.533]}
        rotation={[0, -0.176, 0]}
        scale={0.154}
      >
        <mesh
          geometry={nodes.Cube068.geometry}
          material={materials.lightbrown}
        />
        <mesh
          geometry={nodes.Cube068_1.geometry}
          material={materials["darkbrown.001"]}
        />
        <mesh
          geometry={nodes.Cube068_2.geometry}
          material={materials.lightestbrown}
        />
        <mesh
          geometry={nodes.Cube068_3.geometry}
          material={materials.darkbrown}
        />
        <mesh
          geometry={nodes.Cube068_4.geometry}
          material={materials["pink.001"]}
        />
        <mesh
          geometry={nodes.Cube068_5.geometry}
          material={materials["lightbrown.001"]}
        />
        <mesh
          geometry={nodes.Cube068_6.geometry}
          material={materials["Material.009"]}
        />
        <mesh geometry={nodes.Cube068_7.geometry} material={materials.pink} />
        <mesh
          geometry={nodes.Cube068_8.geometry}
          material={materials["pale white"]}
        />
        <mesh
          geometry={nodes.Cube068_9.geometry}
          material={materials["Material.047"]}
        />
        <mesh
          geometry={nodes.Cube068_10.geometry}
          material={materials["dark brown"]}
        />
        <mesh
          geometry={nodes.Cube068_11.geometry}
          material={materials["Material.050"]}
        />
        <mesh
          geometry={nodes.Cube068_12.geometry}
          material={materials["room_floor.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/final_2.gltf");
